kind: pipeline
type: docker
name: default

steps:
  - name: Push dockerfile to Gitlab
    image: plugins/docker
    settings:
      registry: registry.timolohmann.de
      repo: registry.timolohmann.de/tiloman/abile
      tags:
        - latest
        - 1.0
      username:
        from_secret: gitlab_username
      password:
        from_secret: gitlab_password
      ssh-agent-key:
        from_secret: gitlab_ssh_key
    when:
      branch:
      - main
