kind: pipeline
type: docker
name: default

steps:
#  - name: build
#    image: ruby:3.0.2
#    commands:
#      - apt update
#      - apt install nodejs npm -y
#      - npm install --global yarn
#      - rm config/database.yml
#      - mv config/database.yml.ci config/database.yml
#      - gem install bundler
#      - bundle install --jobs=4
#      - bundle exec rails db:create RAILS_ENV=test
#      - bundle exec rails db:schema:load RAILS_ENV=test
#      - yarn
#      - bundle exec rspec spec
#    volumes:
#      - name: gem-cache
#        path: /bundle
#      - name: tmp
#        path: /drone/src/tmp
#    environment:
#      RAILS_ENV: test
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: abile_test
#      DATABASE_HOST: database
#      PARALLEL_TEST_PROCESSORS: 15
#      TZ: Europe/Berlin

  - name: Push to Docker
    image: plugins/docker
    settings:
      repo: tiloman/abile
      tags: latest
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
      - main
