kind: pipeline
type: docker
name: default

steps:
  - name: Push to Docker
    image: plugins/docker
    settings:
      repo: tiloman/abile
      tags: latest
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
      - main
