development:
  adapter: postgresql
  encoding: unicode
  database: pkvapp_development
  pool: 5
  username: pkv
  password: pmc2000

test:
  adapter: postgresql
  encoding: unicode
  database: pkvapp_test
  pool: 5
  username: pkv
  password: pmc2000
